/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
	public static void main(String[] args) {
		Player pl1 = new Player();
		Player pl2 = new Player();
		TicTacToe game = new TicTacToe(pl1, pl2);

		game.play();
	}

}
